{
 "title": "Nodes metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "CPU avg（5m）",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU iowait（5m）",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "fd allocated",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "node_filefd_allocated{}" }
   ]
  },
  {
   "title": "Node RAM usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 0 },
   "targets": [
    { "expr": "tlos_mem_usage{}" }
   ]
  },
  {
   "title": "Node total RAM Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "tlos_total_ram {}", "legendFormat": "Total RAM " }
   ]
  },
  { "title": "TELOS node metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "TELOS head block num",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "tlos_head_block{}" }
   ]
  },
  {
   "title": "TELOS node statedb memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Memory size Gb" }
   ],
   "targets": [
    { "expr": "tlos_size_of_statedb{}", "legendFormat": "Size of statedb Gb" },
    { "expr": "tlos_usage_of_state {}", "legendFormat": "Usage of statedb Gb" },
    { "expr": "tlos_free_bytes_of_statedb {}", "legendFormat": "Free space of statedb Gb" }
   ]
  },
  {
   "title": "TELOS node reversive blocks db memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Memory size Gb" }
   ],
   "targets": [
    { "expr": "tlos_size_of_reversibledb {}", "legendFormat": "Size of reversible db Gb" },
    { "expr": "tlos_usage_of_reversibledb {}", "legendFormat": "Usage of reversible db Gb" },
    {
     "expr": "tlos_free_bytes_of_reversibledb {}",
     "legendFormat": "Free space of reversible db Gb"
    }
   ]
  },
  {
   "title": "TELOS lib block num",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "tlos_lib_block{}" }
   ]
  },
  {
   "title": "TELOS average CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "expr": "tlos_cpu_usage{}" }
   ]
  },
  { "title": "Host Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1{}", "legendFormat": "1m" },
    { "expr": "node_load5{}", "legendFormat": "5m" },
    { "expr": "node_load15{}", "legendFormat": "15m" }
   ]
  },
  {
   "title": "CPU load over time（%）",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"system\"}[1m]))",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"user\"}[1m]))",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"iowait\"}[1m]))",
     "legendFormat": "Iowait"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{}[1m])",
     "legendFormat": "{{device}}_I/O%"
    }
   ]
  },
  {
   "title": "disk r/w bytes",
   "type": "graph",
   "description": "Read bytes\nWritten bytes",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{}[1m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{}[1m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "iops", "label": "I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{}[1m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{}[1m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "TCP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_netstat_Tcp_CurrEstab{}", "legendFormat": "ESTABLISHED" },
    { "expr": "node_sockstat_TCP_tw{}", "legendFormat": "TCP_tw" },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{}[1m])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{}[1m])",
     "legendFormat": "PassiveOpens"
    },
    { "expr": "node_sockstat_TCP_alloc{}", "legendFormat": "TCP_alloc" },
    { "expr": "node_sockstat_TCP_inuse{}", "legendFormat": "TCP_inuse" }
   ]
  },
  {
   "title": "disk io",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{}[1m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{}[1m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Net IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  }
 ]
}